### ISSUE TITLE
麻烦问下13代平台的完善情况

### ISSUE THREAD

**Issue by East333** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#1]
你好，麻烦问下，现在b760和z790黑苹果方案完善吗？会不会有声卡之类的驱动问题，相比于12代平台会有坑之类的吗？

**Comment by Stick-Study** [comment]
13代基本和12代差不多，声卡起码我看到的都是正常的，只不过睡眠有很大概率会炸。

**Comment by East333** [comment]
是睡眠会崩溃吗

**Comment by Stick-Study** [comment]
> 是睡眠会崩溃吗

哞大说700系列主板，如果睡眠主机不停直接死机开ErP就好；或者可以关ErP，然后用SSDT-RHUB。

有些主板有两个USB主控，外挂的USB主控唤醒优先级就低，设备属性需要强制XHCI acpi-wake-type 1，如果没有这个需要按两下才能唤醒。

不能睡眠的两种情况：
- 某些主板的新BIOS，比如华硕，它会有RTC时钟唤醒，因为它不是PRW的设备，所以它也没法屏蔽，所以也就没法睡眠。
- 某些板载10G网卡也会不停唤醒主机

**Comment by East333** [comment]
了解了 谢谢

**Comment by Stick-Study** [comment]
我觉得微星的主板应该会好一点
