### ISSUE TITLE
6650xt无法4k 高刷

### ISSUE THREAD

**Issue by itechsen** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#11]
**Have You Read My README**

yes
**Question Type**

显示输出高刷
**Description**

之前接的2k@165hz 完美使用 最近买了个4k@144hz的只有4k@60hz选项可以选了 不知道怎么解决

**Comment by Stick-Study** [comment]
macOS Ventura 的 DSC 存在问题，macOS Sonoma 修复了此问题。
所以你要想使用 4K 144Hz 显示器，请升级至 macOS Sonoma。

**Comment by itechsen** [comment]
> macOS Ventura 的 DSC 存在问题，macOS Sonoma 修复了此问题。 所以你要想使用 4K 144Hz 显示器，请升级至 macOS Sonoma。

请问sonoma下原来免驱的博通网卡 现在驱动成熟了吗

**Comment by Stick-Study** [comment]
> > macOS Ventura 的 DSC 存在问题，macOS Sonoma 修复了此问题。 所以你要想使用 4K 144Hz 显示器，请升级至 macOS Sonoma。
> 
> 
> 
> 请问sonoma下原来免驱的博通网卡 现在驱动成熟了吗

我最近没有试过，听别人反馈是能用，如果要是当作生产力就不推荐，如果只是日常用就没问题
