### ISSUE TITLE
ASUS Prime B760M-K D4-CSM 安裝錯誤

### ISSUE THREAD

**Issue by raindy29** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#3]
請問有人試過這張主機板嗎？
一安裝就出現  Err(0xE)  RTGV
EB.WL.PWLFNV
EB.WL.PWLFRTC

試著更改 Enable Change MC__ to MCHC( on ASUS )
也無效

**Comment by Stick-Study** [comment]
您可以上傳一張包括代碼停止的屏幕截圖嗎

**Comment by Stick-Study** [comment]
由於長時間未回复，已暫時將此 issue 關閉。若您仍有問題待解決，請重新打開此 issue。
