### ISSUE TITLE
偶然看到这个项目,先问一下,我用不同作者做的b660 efi,有的能有线上网,有的不能有线上网,会提示没有ip,请问是因为oc引导没配置好吗?

### ISSUE THREAD

**Issue by nizuowanzhenbang** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#4]
偶然看到这个项目,先问一下,我用不同作者做的b660 efi,有的能有线上网,有的不能有线上网,会提示没有ip,请问是因为oc引导没配置好吗?我一直以为i225-V不需要网卡驱动,看了你的文章才知道是需要映射的,能否讲解一下原理?

**Comment by nizuowanzhenbang** [comment]
补充一下我的有线2.5g网卡是英特尔i225-V,我不太懂这个网卡到底是不是免驱

**Comment by Stick-Study** [comment]
> 补充一下我的有线2.5g网卡是英特尔i225-V,我不太懂这个网卡到底是不是免驱

关于它到不到底免躯，这取决于固件里的 Subsystem-ID(正确为E000，错误为0000) 和 Subsystem Vendor-ID(正确为1458，错误为8086) 是否正确。如果这两个是正确的，那么便可以使用 [AppleVTD](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/wiki/AppleVTD_Simplified_Chinese) 提供 **DMA重映射** 以达到免躯（关于DMA重映射在知乎上有详细的解释）。

关于修复这两个 ID，有两种方法，第一种便是使用 SSDT+kext（因为那个kext已经在 macOS Ventura 中被删除了，所以需要手动加载回去）。第二种就是刷固件。

关于无IP，我并没有遇到过，所以我也无法提供建议

如果您无法访问互联网，请通过终端删除以下首选项并重新启动：

* `sudo rm /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist`
* `sudo rm /Library/Preferences/SystemConfiguration/preferences.plist`

如果您仍然无法访问 Internet，请删除以下首选项，然后重新启动：

* `/Library/Preferences/com.apple.networkextension.necp.plist`
* `/Library/Preferences/com.apple.networkextension.plist`
* `/Library/Preferences/com.apple.networkextension.uuidcache.plist`

* 您可以在此仓库的[wiki](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/wiki)页面找到更多信息
