### ISSUE TITLE
tuf gaming b660m plus wifi  +i5 13600k 失败了，一直卡重启。

### ISSUE THREAD

**Issue by eGpx-jqx** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#5]
![20230423_213232.jpg](https://user-images.githubusercontent.com/47662231/233842848-5553b643-2ba8-4100-a9e6-ab9b46dcc5d7.jpg)

![20230327_203650.jpg](https://user-images.githubusercontent.com/47662231/233842865-40165e1e-8ab6-479e-ac39-947466c0692d.jpg)

**Comment by eGpx-jqx** [comment]
![image](https://user-images.githubusercontent.com/47662231/233843125-d80f84e6-2425-46ba-b597-576fc3fa7c6e.png)
![image](https://user-images.githubusercontent.com/47662231/233843134-f5035b9b-61fe-4bad-b0ed-3d46eb95213b.png)
![image](https://user-images.githubusercontent.com/47662231/233843148-e7480725-0aba-4ac2-8433-6cf8d97d2fd6.png)
![image](https://user-images.githubusercontent.com/47662231/233843162-7b69414b-1a61-439e-853b-7d73d97f385a.png)
![image](https://user-images.githubusercontent.com/47662231/233843178-63c522f8-9638-4718-b235-5d82ef1b9762.png)
![image](https://user-images.githubusercontent.com/47662231/233843197-ca51136d-25b6-443f-8221-ada8091e2904.png)
![image](https://user-images.githubusercontent.com/47662231/233843202-1be1e9e7-0db5-427a-ba4e-8298b40f5547.png)
以上是根据up bilibili的配置来改的

**Comment by Stick-Study** [comment]
ACPI 报错，试试把那几个 ACPI 补丁启用吧

**Comment by eGpx-jqx** [comment]
> ACPI 报错，试试把那几个 ACPI 补丁启用吧

都做过尝试， 未起作用。  包括我自己按照官方文档收集及配置的也是无法正确工作。
目前唯一能工作的只有xmb发布的旧版一个efi。

**Comment by eGpx-jqx** [comment]
> > ACPI 报错，试试把那几个 ACPI 补丁启用吧
> 
> 都做过尝试， 未起作用。  包括我自己按照官方文档收集及配置的也是无法正确工作。
> 目前唯一能工作的只有xmb发布的旧版一个efi。

bios中serial port没关闭导致的。 目前OK
