### ISSUE TITLE
请问我的蓝宝石6600XT使用ASUS Z790主板，MacOS Venture13.4显卡有啸叫电流声有办法解决嘛

### ISSUE THREAD

**Issue by xxy6910** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#6]
请问我的蓝宝石6600XT使用ASUS Z790主板，MacOS Venture13.4显卡有啸叫电流声有办法解决嘛；
之前的主板是铭瑄Z790M没发现啸叫电流程；
请问有什么办法解决嘛？

**Comment by Stick-Study** [comment]
啸叫主要是电子元件震动吧
您可以试试用导热贴贴一下那个原料
或者注入PP_XXXPlayTable
