### ISSUE TITLE
MSI H610M-E 卡EB，求大佬指点

### ISSUE THREAD

**Issue by ByyEzz** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#7]

**Comment by ByyEzz** [comment]
我试了一下，先是报错OC: Driver HfsPlus.efi at 0 cannot be loaded - Access Denied! Halting on critical error
然后查到的 UEFI-Quirks-DisableSecurityPolicy  YSE
之后能进去镜像安装了 但是就会卡在
![bbedcb7be117f1953588cfe7503f28e](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/cb292c61-6c34-43ae-8b84-8e89ad108737)
试过其他大佬的MSI B660的EFI，同卡在这一步，求大佬解答

**Comment by ByyEzz** [comment]
请问是BIOS的CFG选项禁用么，我有查到说可能是这个选项没禁用导致的，
![cbfe5b5d4770cb129985d5e16d83511](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/ee18ce24-2b11-4861-9113-4deb2d358699)
我这个BIOS里CFG锁定也已经是禁用状态了，也试过勾选AppleCpuPmCfgLock
AppleXcpmCfgLock，都没效果的

**Comment by Fu-Yuxuan-hub** [comment]
您可以截一下您的EFI文件夹目录吗，因为我对为什么会报「HfsPlus访问拒绝」这个问题没有任何的思路。

其次您也可以尝试一下*config_Raptor_Lake.plist*

**Comment by ByyEzz** [comment]
感谢您的回答，我去尝试一下config_Raptor_Lake.plist
![625518edd24010b68fc5c809c2f90b3](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/36109880-a3bb-428e-95bf-2eb358000417)
![c31e352c1095f028f5aa6ebd15c41dc](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/ec43934a-7158-4766-bef8-b6301ccf475f)
![5d5f18f7e42426e7b65e40229e37d7d](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/f109f99a-dd51-4d1b-92c5-bc5f06899fa4)

**Comment by ByyEzz** [comment]
您好，我刚刚尝试了下config_Raptor_Lake.plist，这次不会报「HfsPlus访问拒绝」，可以直接进入镜像安装界面，刚刚卡EB界面变成了如下图
![734422a83ec4a7f008d0379bcdc865c](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/912fe323-02c2-4290-ab83-ffed82e6fc8c)
![9c68db08b2d7e076bbe8e1636c77c1f](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/4dc04b53-6560-4fc3-a999-0dba4e0087da)
原来安装时卡白苹果LOGO的下方现在多了一个进度条，不过按其他的教程来说，第一次的安装读条应该会很快，这个进度条是始终卡死状态

**Comment by Fu-Yuxuan-hub** [comment]
> 您好，我刚刚尝试了下config_Raptor_Lake.plist，这次不会报「HfsPlus访问拒绝」，可以直接进入镜像安装界面，刚刚卡EB界面变成了如下图
> 
> ![734422a83ec4a7f008d0379bcdc865c](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/912fe323-02c2-4290-ab83-ffed82e6fc8c)
> 
> ![9c68db08b2d7e076bbe8e1636c77c1f](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/4dc04b53-6560-4fc3-a999-0dba4e0087da)
> 
> 原来安装时卡白苹果LOGO的下方现在多了一个进度条，不过按其他的教程来说，第一次的安装读条应该会很快，这个进度条是始终卡死状态

您可以试试启用那些ACPI补丁

不过它卡ACPI，为什么出现苹果的Logo和进度条呢:-)

**Comment by ByyEzz** [comment]
不好意思，刚刚发现卡白苹果进度条是我错Copy了以前配置的一个EFI文件
刚刚尝试了一下启用ACPI补丁，目前还是会卡在这个界面
![399b448bd639f1f0adf49cf26402f4a](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/136185926/085aed21-3e46-4bdd-8a1b-f554fbe185d1)

**Comment by Fu-Yuxuan-hub** [comment]
1.请试试启用前两个补丁
![截屏2023-06-15 22 34 41](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/assets/74492520/0c281fd8-42ba-4bee-9622-1b4804caeeb9)

2.请查看 *BIOS* 中 *Serial Port* 是否已经关闭

**Comment by Fu-Yuxuan-hub** [comment]
COM Port有没有呢

**Comment by ByyEzz** [comment]
> COM Port有没有呢

也没有

**Comment by Fu-Yuxuan-hub** [comment]
我认为我弄不好他😭能力有限，实在抱歉。我只知道 ACPI 报错可能是由 *MC* 引起， *XH_ADLS3* 和 *Serial Port* 等引起。所以我的建议就是您可以试试在 Windows 下使用 [SSDTTime](https://github.com/corpnewt/SSDTTime) 生成一套 SSDT，然后进行尝试。

参见  [【Windows&macOS】完美双系统系列教程第5集，编译SSDT](https://www.bilibili.com/video/BV19q4y1h7eq/?share_source=copy_web)
