### ISSUE TITLE
13600kf跑分异常

### ISSUE THREAD

**Issue by itechsen** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#9]
用的技嘉Z790M小雕配13600KF.geekbench5下，单核心1300左右。我看正常是2000+的。。。不知道问题出在哪。现在近乎完美，就差这个CPU性能释放了。。。求大神解惑

**Comment by Stick-Study** [comment]
应该是没有睿频导致的，请尝试替换以下 kext，然后使用 Intel Power Gadget 查看是否已正确睿频

[CPUFriendDataProvider.kext.zip](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/files/12908640/CPUFriendDataProvider.kext.zip)
[CPUFriend.kext.zip](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/files/12908641/CPUFriend.kext.zip)

**Comment by itechsen** [comment]
更换完这两个文件跑分正常了。谢谢。还有一个小问题，我这个Mac Pro下面怎么没有显示年份哈
![9b0c5ac7559de8c4a46346f096afa4be](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/assets/7986286/b1932d2a-b61f-41e2-8e54-b7c9c21ef13c)

![IMG_0405](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/assets/7986286/9159fa44-2990-4265-bf5e-6a17993279be)

**Comment by Stick-Study** [comment]
> 更换完这两个文件跑分正常了。谢谢。还有一个小问题，我这个Mac Pro下面怎么没有显示年份哈
> 
> ![9b0c5ac7559de8c4a46346f096afa4be](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/assets/7986286/b1932d2a-b61f-41e2-8e54-b7c9c21ef13c)
> 
> 
> 
> ![IMG_0405](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/assets/7986286/9159fa44-2990-4265-bf5e-6a17993279be)
> 
> 

抱歉，不了解这个😂可以试试重新换一个三码并 Reset nvram

**Comment by itechsen** [comment]
> > 更换完这两个文件跑分正常了。谢谢。还有一个小问题，我这个Mac Pro下面怎么没有显示年份哈
> > ![9b0c5ac7559de8c4a46346f096afa4be](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/assets/7986286/b1932d2a-b61f-41e2-8e54-b7c9c21ef13c)
> > ![IMG_0405](https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790/assets/7986286/9159fa44-2990-4265-bf5e-6a17993279be)
> 
> 抱歉，不了解这个😂可以试试重新换一个三码并 Reset nvram

大神，换过三码试过了木有用哈。不纠结这个了哈，现在出现睡眠后，唤不醒的问题。。。键盘灯亮，主板风扇转，就是没有输出信号。
